import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export default function BrochureOutput({ content, isStreaming, companyName }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMd = () => {
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${companyName.replace(/\s+/g, '-').toLowerCase()}-brochure.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = () => {
    const contentEl = document.getElementById('brochure-print-content');
    if (!contentEl) return;

    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>${companyName} Brochure</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
          *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
          body {
            font-family: 'Inter', system-ui, sans-serif;
            font-size: 11pt;
            line-height: 1.75;
            color: #1a1a2e;
            background: #fff;
            padding: 48pt 52pt;
            max-width: 780px;
            margin: 0 auto;
          }
          .cover {
            margin-bottom: 28pt;
            padding-bottom: 16pt;
            border-bottom: 2px solid #7c3aed;
          }
          .cover h1 {
            font-size: 26pt;
            font-weight: 800;
            color: #0f0a1e;
            letter-spacing: -0.5px;
            margin-bottom: 4pt;
          }
          .cover p { font-size: 9pt; color: #888; }
          h2 {
            font-size: 14pt;
            font-weight: 700;
            color: #1a1a2e;
            margin-top: 22pt;
            margin-bottom: 8pt;
            padding-bottom: 4pt;
            border-bottom: 1px solid #e5e7eb;
          }
          h3 {
            font-size: 11.5pt;
            font-weight: 600;
            color: #2d2d4e;
            margin-top: 14pt;
            margin-bottom: 5pt;
          }
          p { margin-bottom: 8pt; color: #374151; }
          ul, ol { padding-left: 18pt; margin-bottom: 8pt; }
          li { margin-bottom: 3pt; color: #374151; }
          strong { color: #111; font-weight: 600; }
          em { color: #6d28d9; font-style: italic; }
          hr { border: none; border-top: 1px solid #e5e7eb; margin: 16pt 0; }
          h2, h3 { page-break-after: avoid; }
          p, li { page-break-inside: avoid; }
        </style>
      </head>
      <body>
        <div class="cover">
          <h1>${companyName}</h1>
          <p>Company Brochure &middot; Generated by BrochureAI</p>
        </div>
        ${contentEl.innerHTML}
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="animate-fade-in-up">
      {/* Output card */}
      <div className="glass gradient-border overflow-hidden">
        {/* Card header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 px-4 sm:px-6 py-4 border-b border-white/[0.06]">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 flex-shrink-0 rounded-lg bg-gradient-to-br from-violet-500/20 to-blue-500/20 border border-violet-500/20 flex items-center justify-center">
              <svg className="w-4 h-4 text-violet-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5}
                  d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <div>
              <p className="text-sm font-semibold text-slate-200">{companyName} Brochure</p>
              <p className="text-xs text-slate-500">{isStreaming ? 'Generating…' : 'Ready'}</p>
            </div>
          </div>

          {/* Actions */}
          {!isStreaming && content && (
            <div className="flex items-center gap-2 flex-wrap">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 rounded-lg border border-white/[0.08] bg-white/[0.04] px-3 py-1.5 text-xs font-medium text-slate-300 hover:bg-white/[0.08] hover:text-slate-100 transition-all"
              >
                {copied ? (
                  <>
                    <svg className="w-3.5 h-3.5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span className="text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5}
                        d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                    </svg>
                    Copy
                  </>
                )}
              </button>

              <button
                onClick={handleDownloadMd}
                className="flex items-center gap-1.5 rounded-lg border border-white/[0.08] bg-white/[0.04] px-3 py-1.5 text-xs font-medium text-slate-300 hover:bg-white/[0.08] hover:text-slate-100 transition-all"
              >
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5}
                    d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                .md
              </button>

              <button
                onClick={handleDownloadPdf}
                className="flex items-center gap-1.5 rounded-lg border border-violet-500/30 bg-violet-500/10 px-3 py-1.5 text-xs font-medium text-violet-300 hover:bg-violet-500/20 hover:text-violet-200 transition-all"
              >
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5}
                    d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                </svg>
                PDF
              </button>
            </div>
          )}
        </div>

        {/* Content */}
        <div className="p-4 sm:p-6 max-h-[65vh] overflow-y-auto scrollbar-thin" id="brochure-print-content">
          <div className={`brochure-prose ${isStreaming ? 'streaming-cursor' : ''}`}>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {content}
            </ReactMarkdown>
          </div>
        </div>
      </div>
    </div>
  );
}
